### ISSUE TITLE
Intel Scikit-learn vs daal4py

### ISSUE THREAD

**Issue by abhi-84** [IntelPython/daal4py#190]
Both Intel Scikit-learn and daal4py uses Intel DAAL at backend so what's the basic difference? One thing that I for to know is daa;4py can be used during Scaling due to availability of Intel MPI. I hopw I am correct! Any thing else?
please help

**Comment by Alexander-Makaryev** [comment]
@abhi-84 
Hello, excuse me for a late answer,

Daal4py is Python API for DAAL, so it contains a large set of algorithms that are available in original DAAL.
In Scikit-Learn we patch only subset of algorithms.
We are providing algorithms with the same behavior which are able to pass original test suite and can be used in "drop-and-replace" way.
At this moment it is not possible to replace more algorithms in Scikit-Learn because DAAL has some differences in parameters, implementation and etc.
But we are working on it.

Call of patched Scikit-Learn make a lot of additional computations like various checks of input data, so it can be slower then call of daal4py directly.

I hope that this answer will makes it little bit clear.
